nutritional_value = {
    "apple": {
        "per_100g": {
            "calories": 52,
            "protein": 0.3,
            "carbohydrates": 14,
            "sugars": 10,
            "dietary_fiber": 2.4,
            "fat": 0.2,
            "vitamin_c": 4.6,
            "potassium": 107,
        },
        "per_item": {
            "calories": 52,
            "protein": 0.3,
            "carbohydrates": 14,
            "sugars": 10,
            "dietary_fiber": 2.4,
            "fat": 0.2,
            "vitamin_c": 4.6,
            "potassium": 107,
        },
    },
    "apricot": {
        "per_100g": {
            "calories": 48,
            "protein": 1.4,
            "carbohydrates": 11,
            "sugars": 9,
            "dietary_fiber": 2,
            "fat": 0.4,
            "vitamin_c": 10,
            "potassium": 259,
        },
        "per_item": {
            "calories": 48,
            "protein": 1.4,
            "carbohydrates": 11,
            "sugars": 9,
            "dietary_fiber": 2,
            "fat": 0.4,
            "vitamin_c": 10,
            "potassium": 259,
        },
    },
    "avocado": {
        "per_100g": {
            "calories": 160,
            "protein": 2,
            "carbohydrates": 9,
            "sugars": 0.7,
            "dietary_fiber": 7,
            "fat": 15,
            "saturated_fat": 2.1,
            "monounsaturated_fat": 9.8,
            "vitamin_c": 10,
            "potassium": 485,
        },
        "per_item": {
            "calories": 160,
            "protein": 2,
            "carbohydrates": 9,
            "sugars": 0.7,
            "dietary_fiber": 7,
            "fat": 15,
            "saturated_fat": 2.1,
            "monounsaturated_fat": 9.8,
            "vitamin_c": 10,
            "potassium": 485,
        },
    },
    "banana": {
        "per_100g": {
            "calories": 89,
            "protein": 1.1,
            "carbohydrates": 23,
            "sugars": 12,
            "dietary_fiber": 2.6,
            "fat": 0.3,
            "vitamin_c": 8.7,
            "potassium": 358,
        },
        "per_item": {
            "calories": 89,
            "protein": 1.1,
            "carbohydrates": 23,
            "sugars": 12,
            "dietary_fiber": 2.6,
            "fat": 0.3,
            "vitamin_c": 8.7,
            "potassium": 358,
        },
    },
    "eggplant": {
        "per_100g": {
            "calories": 25,
            "protein": 1,
            "carbohydrates": 6,
            "sugars": 3.2,
            "dietary_fiber": 3,
            "fat": 0.2,
            "vitamin_c": 2.2,
            "potassium": 229,
        },
        "per_item": {
            "calories": 25,
            "protein": 1,
            "carbohydrates": 6,
            "sugars": 3.2,
            "dietary_fiber": 3,
            "fat": 0.2,
            "vitamin_c": 2.2,
            "potassium": 229,
        },
    },
    "kiwi": {
        "per_100g": {
            "calories": 61,
            "protein": 1.1,
            "carbohydrates": 15,
            "sugars": 9,
            "dietary_fiber": 3,
            "fat": 0.5,
            "vitamin_c": 92.7,
            "potassium": 312,
        },
        "per_item": {
            "calories": 61,
            "protein": 1.1,
            "carbohydrates": 15,
            "sugars": 9,
            "dietary_fiber": 3,
            "fat": 0.5,
            "vitamin_c": 92.7,
            "potassium": 312,
        },
    },
    "mango": {
        "per_100g": {
            "calories": 60,
            "protein": 0.8,
            "carbohydrates": 15,
            "sugars": 14,
            "dietary_fiber": 1.6,
            "fat": 0.4,
            "vitamin_c": 36.4,
            "potassium": 168,
        },
        "per_item": {
            "calories": 60,
            "protein": 0.8,
            "carbohydrates": 15,
            "sugars": 14,
            "dietary_fiber": 1.6,
            "fat": 0.4,
            "vitamin_c": 36.4,
            "potassium": 168,
        },
    },
    "mango_red": {
        "per_100g": {
            "calories": 60,
            "protein": 0.8,
            "carbohydrates": 15,
            "sugars": 14,
            "dietary_fiber": 1.6,
            "fat": 0.4,
            "vitamin_c": 36.4,
            "potassium": 168,
        },
        "per_item": {
            "calories": 60,
            "protein": 0.8,
            "carbohydrates": 15,
            "sugars": 14,
            "dietary_fiber": 1.6,
            "fat": 0.4,
            "vitamin_c": 36.4,
            "potassium": 168,
        },
    },
    "orange": {
        "per_100g": {
            "calories": 47,
            "protein": 0.9,
            "carbohydrates": 12,
            "sugars": 9,
            "dietary_fiber": 2.4,
            "fat": 0.1,
            "vitamin_c": 53.2,
            "potassium": 181,
        },
        "per_item": {
            "calories": 47,
            "protein": 0.9,
            "carbohydrates": 12,
            "sugars": 9,
            "dietary_fiber": 2.4,
            "fat": 0.1,
            "vitamin_c": 53.2,
            "potassium": 181,
        },
    },
    "pear": {
        "per_100g": {
            "calories": 57,
            "protein": 0.4,
            "carbohydrates": 15,
            "sugars": 10,
            "dietary_fiber": 3.1,
            "fat": 0.1,
            "vitamin_c": 4.3,
            "potassium": 116,
        },
        "per_item": {
            "calories": 57,
            "protein": 0.4,
            "carbohydrates": 15,
            "sugars": 10,
            "dietary_fiber": 3.1,
            "fat": 0.1,
            "vitamin_c": 4.3,
            "potassium": 116,
        },
    },
    "pineapple": {
        "per_100g": {
            "calories": 50,
            "protein": 0.5,
            "carbohydrates": 13,
            "sugars": 10,
            "dietary_fiber": 1.4,
            "fat": 0.1,
            "vitamin_c": 47.8,
            "potassium": 109,
        },
        "per_item": {
            "calories": 50,
            "protein": 0.5,
            "carbohydrates": 13,
            "sugars": 10,
            "dietary_fiber": 1.4,
            "fat": 0.1,
            "vitamin_c": 47.8,
            "potassium": 109,
        },
    },
}

nutrition_weights = {
    "calories": "calories",
    "protein": "grams",
    "carbohydrates": "grams",
    "sugars": "grams",
    "dietary_fiber": "grams",
    "fat": "grams",
    "saturated_fat": "grams",
    "monounsaturated_fat": "grams",
    "vitamin_c": "milligrams",
    "potassium": "milligrams",
}

food_weights = {
    "apple": 182,
    "apricot": 35,
    "avocado": 200,
    "banana": 118,
    "eggplant": 450,
    "kiwi": 76,
    "mango": 336,
    "mango_red": 336,
    "orange": 131,
    "pear": 178,
    "pineapple": 452
}